stackable-items:
  suspicious_stew: 32
  rabbit_stew: 32
  mushroom_stew: 32
  beetroot_soup: 32
  potion: 8
  splash_potion: 8
  lingering_potion: 8
  oak_boat: 4
  spruce_boat: 4
  birch_boat: 4
  jungle_boat: 4
  acacia_boat: 4
  dark_oak_boat: 4
  cherry_boat: 4
  bamboo_raft: 4
  pale_oak_boat: 4
  oak_chest_boat: 4
  spruce_chest_boat: 4
  birch_chest_boat: 4
  jungle_chest_boat: 4
  acacia_chest_boat: 4
  dark_oak_chest_boat: 4
  cherry_chest_boat: 4
  bamboo_chest_raft: 4
  pale_oak_chest_boat: 4
  minecart: 4
  hopper_minecart: 4
  chest_minecart: 4
  command_block_minecart: 4
  furnace_minecart: 4
  tnt_minecart: 4
  saddle: 16
